# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsos1xHToyYqM48xzKhSpgx3SX2V1FqQ
"""
# 
# pip install pandasai==0.8.4
from pandasai import SmartDataframe
# You can instantiate a SmartDataframe with a path to a CSV file
sdf = SmartDataframe("Datasets/population.csv")

response = sdf.chat("احسب المعادلة التالية تايلند عدد السكان + 5 - 20")
print(response)
# Output: 247 loans have been paid off by men.

from pandasai import SmartDataframe
from pandasai.llm.local_llm import LocalLLM

ollama_llm = LocalLLM(api_base="http://localhost:11434/v1", model="llama3")
df = SmartDataframe("population.csv", config={"llm": ollama_llm})

response = sdf.chat("ارسم رسم بياني عامودي للدول اسماء الاعمدة بالعربي")
print(response)

